/*
 * Non-Secure Callable (NSC) API exported by the Secure world.
 *
 * Shared by both images: the Secure build defines these functions with
 * CMSE_NS_ENTRY, the Non-Secure build links against the veneers in
 * secure_nsclib.o generated by the Secure link (--cmse-implib).
 */
#ifndef SECURE_NSC_H
#define SECURE_NSC_H

#include <stdint.h>

/* Provided by system_stm32l5xx_s.c (ST template). */
uint32_t SECURE_SystemCoreClockUpdate(void);

/* M1: trivial Secure service, proves the NS -> S -> NS round trip. */
uint32_t SECURE_Add(uint32_t a, uint32_t b);

/* Number of SECURE_Add calls; the counter itself lives in Secure SRAM. */
uint32_t SECURE_GetCallCount(void);

#endif /* SECURE_NSC_H */
